### ISSUE TITLE
Users can search for recipes on the Search Page.

### ISSUE THREAD

**Issue by lisa-doan** [lisa-doan/final-project#1]
## 💰 Motivation
Users can search for recipes on the Search Page.

## 🖼️ Wireframe
<img src="https://user-images.githubusercontent.com/77419144/113761648-8db6e300-96cc-11eb-8c1e-0b0dda145daa.png" width ="250">

## ✅ Task List
- [x] Create component module  
- [x] Create a HTML model/skeleton and style with CSS
- [x] Add a class react component to create a form element
- [x] Add an input element to form and make it a required field
- [x] Add a method to request an API call.
- [x] Add an OnClick function to the suggested search items
- [x] Remove all CSS styling that had no affect or was otherwise unnecessary.
- [x] Test all functionality again in a private browsing session.
- [x] Fix all errors.
