### ISSUE TITLE
Users can view a list of results on the Search Page.

### ISSUE THREAD

**Issue by lisa-doan** [lisa-doan/final-project#2]
## 💰 Motivation
Users can view a list of results on the Search Page.

## 🖼️ Wireframe
<img src="https://user-images.githubusercontent.com/77419144/113759788-57786400-96ca-11eb-8790-b827858a2aff.png" width ="250">

## ✅ Task List
- [x] Create a component for results
- [x] Create cards for results
- [x] Use map to render list
- [x] Remove all CSS styling that had no affect or was otherwise unnecessary.
- [x] Test all functionality again in a private browsing session.
- [x] Fix all errors.
