### ISSUE TITLE
Users can view a recipe on the Recipe Page.

### ISSUE THREAD

**Issue by lisa-doan** [lisa-doan/final-project#4]
## 💰 Motivation
Users can view a recipe on the Recipe Page.

## 🖼️ Wireframe
<img src="https://user-images.githubusercontent.com/77419144/113759788-57786400-96ca-11eb-8790-b827858a2aff.png" width ="250"><img src="https://user-images.githubusercontent.com/77419144/114650376-01418d00-9c97-11eb-8b18-527ea0a87a7b.png" width ="250">

## ✅ Task List

- [x] Add an OnClick function to the image and recipe name
- [x] Create recipe page
- [x] Add an OnClick function to the back arrow icon
- [x] Remove all CSS styling that had no affect or was otherwise unnecessary.
- [x] Test all functionality again in a private browsing session.
- [x] Fix all errors.
